# Generated by Django 4.0.3 on 2022-04-09 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('41fd4323-d862-4031-8270-94ab6cf015fa'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e830ff50-d66f-4408-ae48-e9513ee18bb2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
    ]
