# Generated by Django 4.0.3 on 2022-04-09 15:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_worklogs_alter_brand_id_alter_car_id_and_more'),
        ('rest_auth', '0002_alter_client_id_alter_user_id_alter_client_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='api.position'),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6091d488-a936-4dd0-a288-7d853838a389'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4c36d498-9309-4eb2-bc46-fa5a44b84e1a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
