# Generated by Django 4.0.3 on 2022-05-02 14:08

import datetime
import uuid

import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_auth", "0002_client_created_at_alter_client_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 5, 2, 17, 8, 47, 725676)
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="id",
            field=model_utils.fields.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="id",
            field=model_utils.fields.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=model_utils.fields.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="worklogs",
            name="id",
            field=model_utils.fields.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
