# Generated by Django 4.0.3 on 2022-05-02 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0003_alter_client_created_at_alter_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 17, 13, 55, 102942)),
        ),
    ]
