# Generated by Django 4.0.3 on 2022-04-09 15:35

from django.db import migrations


def apply_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'master-receiver'),
        Group(name=u'master-regular'),
    ])
    

class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0003_user_position_user_salary_alter_client_id_and_more'),
    ]

    operations = [
        migrations.RunPython(apply_groups, None)
    ]
    
