# Generated by Django 4.0.3 on 2022-04-09 15:36

from django.db import migrations, models
import rest_auth.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0004_auto_20220409_1835'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', rest_auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9b46ce9f-859b-4868-a7ea-0161800a4a4d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23620ad8-cec0-4647-9940-e0e2e0b83bbe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
