# Generated by Django 4.0.3 on 2022-05-05 17:14

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_auth", "0004_alter_client_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 5, 5, 20, 14, 31, 452707)
            ),
        ),
        migrations.AlterField(
            model_name="worklogs",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worklogs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
