# Generated by Django 4.0.3 on 2022-05-05 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0005_alter_client_created_at_alter_worklogs_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 20, 18, 46, 696126)),
        ),
    ]
