# Generated by Django 4.0.3 on 2022-04-16 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0005_alter_user_managers_alter_client_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30bce665-4dbc-4f2e-a3db-f9a819e31d7f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4cd409ca-c771-452d-b9f9-3fb2ef65ccb2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
