# Generated by Django 4.0.3 on 2022-05-08 13:16

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_auth", "0006_alter_client_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="salary",
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 5, 8, 16, 16, 28, 239278)
            ),
        ),
    ]
