# Generated by Django 4.0.3 on 2022-04-16 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0006_alter_client_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('15e95b30-6f02-43a7-80b3-07b77d67a439'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b2e0bd9c-4b4d-4a37-a74c-84cd2038fe3d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
