# Generated by Django 4.0.3 on 2022-04-04 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5f1110fd-cd0c-4ce1-9444-158e5b86a4d5'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('781e6a21-cf14-453f-b358-bc080691cb90'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ea265bc9-8768-49a3-8095-67118fe41ad1'), editable=False, primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='masters', to='api.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'masters',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bcf191e3-effc-4074-a2d1-1a28c91b8aba'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='models', to='api.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4f9b7971-687e-41c9-a906-7be6e72cb0a7'), editable=False, primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=15)),
                ('plate_number', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('power', models.DecimalField(decimal_places=1, max_digits=4)),
                ('engine_size', models.DecimalField(decimal_places=1, max_digits=2)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cars', to='api.carmodel')),
            ],
        ),
    ]
