# Generated by Django 4.0.3 on 2022-04-04 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5dd74d7d-e211-4c9d-a4cf-053131ae43e4'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b80937c4-d2fd-4cde-9b1b-d7f4bb21ab2e'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6cfdb0fc-8b51-46c1-9d43-9f6da74cddeb'), editable=False, primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='masters', to='api.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'masters',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('25780711-89ca-450f-9670-92644d880da8'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='models', to='api.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e00162fb-941e-479f-9599-1a740426b4f5'), editable=False, primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=15)),
                ('plate_number', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('power', models.DecimalField(decimal_places=1, max_digits=4)),
                ('engine_size', models.DecimalField(decimal_places=1, max_digits=2)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cars', to='api.carmodel')),
            ],
        ),
    ]
