# Generated by Django 4.0.3 on 2022-04-09 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_brand_id_alter_car_id_alter_carmodel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worklogs',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c6bcd27e-b1e6-43dd-b09b-9d3a47d16941'), editable=False, primary_key=True, serialize=False)),
                ('timeworked', models.DecimalField(decimal_places=2, max_digits=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'worklogs',
            },
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4303b88-e9b9-47be-9a66-fec722291b8b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b37b8aee-736c-4981-bbe5-80c844ffc504'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20c3ba40-716c-4361-a05a-c873fea6796f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5f8b16c1-161c-43bd-8922-2bacb345a5c5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Master',
        )
    ]
