# Generated by Django 4.0.3 on 2022-04-09 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_worklogs_alter_brand_id_alter_car_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.UUIDField(default=uuid.UUID('974ed503-fea2-49d8-9fca-3af4d747ca79'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e3f5c0e9-13e0-4d76-bfb8-9c43e95fbe2a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c218ac02-ff80-49da-8c9e-8ace2b1465aa'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('84c71865-bf8a-4f0d-ad78-4a7efab35312'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worklogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a4fdeb57-d627-4602-b42e-085723383493'), editable=False, primary_key=True, serialize=False),
        ),
    ]
