# Generated by Django 4.0.3 on 2022-04-23 14:46

from django.db import migrations, models
import django
from django.conf import settings
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0008_position_alter_client_id_alter_user_id_worklogs_and_more'),
        ('api', '0005_alter_brand_id_alter_car_id_alter_carmodel_id_and_more'),
    ]

    operations = [
       
    ]
