# Generated by Django 4.0.3 on 2022-05-02 14:08

import uuid

import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_process", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="ended_at",
        ),
        migrations.RemoveField(
            model_name="job",
            name="started_at",
        ),
        migrations.AddField(
            model_name="job",
            name="end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end"),
        ),
        migrations.AddField(
            model_name="job",
            name="start",
            field=models.DateTimeField(blank=True, null=True, verbose_name="start"),
        ),
        migrations.AlterField(
            model_name="job",
            name="id",
            field=model_utils.fields.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("Открыта", "Открыта"),
                    ("В работе", "В работе"),
                    ("Выполнена", "Выполнена"),
                    ("Отложена", "Отложена"),
                ],
                db_index=True,
                default="Открыта",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
