# Generated by Django 4.0.3 on 2022-05-05 17:14

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_process", "0003_remove_job_end_remove_job_start_job_ended_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("Открыта", "Открыта"),
                    ("В работе", "В работе"),
                    ("Выполнена", "Выполнена"),
                    ("Отложена", "Отложена"),
                ],
                db_index=True,
                default="opened",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
