# Generated by Django 4.0.3 on 2022-05-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0013_alter_client_created_at'),
        ('work_process', '0004_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RestrictedError, related_name='jobs', to='rest_auth.client'),
        ),
    ]
