# Generated by Django 4.0.3 on 2022-05-10 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_process', '0008_rename_favour_id_favourspositions_favour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'workplaces',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='work_process.workplaces'),
        ),
    ]
