"""initial

Revision ID: 9527eb0e043f
Revises: 
Create Date: 2022-03-07 18:18:53.429199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9527eb0e043f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
