# Generated by Django 4.0.3 on 2022-05-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bonuses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balancehistory",
            name="status",
        ),
        migrations.AlterField(
            model_name="balancehistory",
            name="value",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="bonusbalance",
            name="balance",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
